POST http://localhost:3333/video HTTP/1.1
content-type: application/json  

{
    "title": "Video 2",
    "description": "Descrição do Video 2",
    "url": "https://www.youtube.com/watch?v=AyqlQWpaNqg"
}

###

GET http://localhost:3333/video HTTP/1.1

###
 
PUT http://localhost:3333/video/i2b72b216-cf87-4a48-98f6-832526b09d18 HTTP/1.1
content-type: application/json  

{
    "title": "Video 2",
    "description": "Descrição do Video 2",
    "url": "https://www.youtube.com/watch?v=AyqlQWpaNqg"
}

###

DELETE http://localhost:3333/video/8b38fdd8-b1da-45f6-b628-2666d7253102 HTTP/1.1
